### ISSUE TITLE
Add Waffle.io webhooks

### ISSUE THREAD

**Issue by aendrew** [github-tools/github#238]
This is another one for @michael given I don't have admin access.

@michael — Could you please login to waffle.io and grant permission to it to create webhooks? Otherwise it won't update without interaction from a user (probably just me). Thanks!

<img width="1440" alt="screen shot 2015-10-19 at 11 36 28" src="https://cloud.githubusercontent.com/assets/185041/10575642/c4e96f70-7655-11e5-9aa0-2e186407ec4f.png">

**Comment by michael** [comment]
I'm a bit hesitant as I need to give waffle.io read+write access to all my public repos.

![image](https://cloud.githubusercontent.com/assets/2931/10576380/26a48a08-7663-11e5-8bbb-f8e1b0a6ddf3.png)

Or is there a per-repository way?

**Comment by aendrew** [comment]
@michael Hmm, not from what I can tell. Their rationale is [here](https://github.com/waffleio/waffle.io/wiki/FAQs#oauth-permissions).

I'll ping them on Twitter and ask if there's a way to manually create webhooks.

**Comment by aendrew** [comment]
Apparently there's not. :P

I've already given Waffle access to all of my repos, I trust what they're doing and enough people are using them. @Michael, if you give me admin access, I could probably add the webhooks without you having to give them access to all of your repos?

**Comment by AurelioDeRosa** [comment]
In regard of this, a solution might be to create an organization and move this repository to it?

**Comment by aendrew** [comment]
I wouldn't be opposed. Would also really help with administrative stuff moving forward.

**Comment by Neirum** [comment]
ALLA

**Comment by DanielRuf** [comment]
waffle.io does not exists anymore so this is obsolete.
