### ISSUE TITLE
Move library to new organisation

### ISSUE THREAD

**Issue by aendrew** [github-tools/github#263]
We've been discussing in the Gitter channel about creating a new parent organisation to collect various bits of code (specifically JavaScript at the moment but could be expanded to other languages or extensions of JS like TypeScript) that interact with GitHub, mainly those that use Github.js but not exclusively (Some examples might be [github-release-notes](https://github.com/alexcanessa/github-release-notes) — the author, @alexcanessa, has already expressed interest in the plan — and my [Axis for GitHub](https://github.com/aendrew/Axis-GitHub) project).

`githubjs` is taken and apparently active (I've contacted GitHub's support team, asking about claiming that org name due to the lack of visible activity in that org, but apparently it is active to some degree). Thus we've started compiling a list of alternative names:
- `github-js`
- `github-tools`
- `GitHub4JS`
- `Githug`
- `GitHubFriends`

Moving the library to a new org would help enormously with administration (adding webhooks, etc.) and help ensure github.js continues to be supported into the future. 

Any thoughts, @michael? Whether we do this is ultimately contingent upon whether you're willing to move the repo to a new org.

That said, for this to be successful, we also need feedback from community stakeholders. Please, if you either use or contrinute to github.js and have a strong opinion, post it here!

Thanks, everyone!

**Comment by AurelioDeRosa** [comment]
Thank you for this great summary @aendrew!

**Comment by AurelioDeRosa** [comment]
Any update on this?

**Comment by clayreimann** [comment]
We also probably need to come up with a name that doesn't start with `github` to make their legal team happy. The package `js-github-api` appears to be free on NPM, thoughts @AurelioDeRosa @aendrew?

Also: I've been chatting with @michael and he says that email is the channel he's likely to respond to (he doesn't monitor mentions/gitter/twitter/etc.)

**Comment by AurelioDeRosa** [comment]
Hi @clayreimann.

The original idea was to potentially on-board projects not necessarily written in JavaScript (e.g. PHP), that's why "GitHub tools". I appreciate that GitHub might not like the name, so I'm open for discussion. The libraries there (mine and @alexcanessa's one) will release a new update very soon, so it might be a good time to revamp the idea of a team. @andrewholsted might be interested in releasing a TypeScript version of GitHub.js, so there is a good amount of work to do.

**Comment by alexcanessa** [comment]
Thanks for the summary @aendrew, as @AurelioDeRosa said, our libraries are going to release new important updates.

I'm still thinking it would be very nice to have everything wrapped up in one organisation.
On my side, I'm trying to align to the main `githubjs` repo every time it is released.

Just remember that **github** complained to us about using names that start with `github`.
I'm also very keen to help in any of the projects that belong to the organisation.

**Comment by aendrew** [comment]
@AurelioDeRosa @andrewholsted re: writing a TypeScript version of github.js — as somebody who's used TypeScript a fair bit at this point, and because github.js is now awesome and modern (Huge kudos to all who worked on that btw — I used it a few weeks ago and the experience was _excellent_), it's probably more worthwhile to just write a TypeScript definition, which can then be distributed with the library. That way there won't be any code divergence, and TypeScript users then only have one version of the library to choose from.

**Comment by AurelioDeRosa** [comment]
This sounds like a good plan. Will you be able to do it?

**Comment by aendrew** [comment]
@AurelioDeRosa I'd planned to at one point, though this year has been an absolutely insane amount of busy thus far and don't want to commit to anything when somebody else already is considering doing so. If there hasn't been any progress in a couple months I may consider it.

**Comment by mtscout6** [comment]
Moving it to github-tools org makes the most sense to me since a number of the collaborators on this repo are also members of that organization. I like that that org's name is not tied to any specific language. If github is not keen on the name, than it's easier to just change the name of that organization with their advice when that time comes.

**Comment by clayreimann** [comment]
@AurelioDeRosa @aendrew et. al. if we want to do this we should send Micael an email. He's said that he doesn't really pay attention to GH issues, gitter, or twitter; so if we want to make this happen we'll need to ping him directly.

**Comment by AurelioDeRosa** [comment]
I think we might want to arrive to a conclusion before sending an email to Michael.

**Comment by mtscout6** [comment]
I vote github-tools org since it already exists.

**Comment by aendrew** [comment]
This has been done long ago, so closing this issue.
