### ISSUE TITLE
[Feature request] Bio doesn't support markdown

### ISSUE THREAD

**Issue by megaxlr** [github-tools/github#344]
The new Bio system doesn't support Markdown.

**Comment by GameKing-XD** [comment]
+1

**Comment by clayreimann** [comment]
Can you clarify what API you're referring to? There is no bio method that I can see.

**Comment by megaxlr** [comment]
The bio text area on the following link:

https://github.com/settings/profile

**Comment by clayreimann** [comment]
So you're requesting that the `user.bio` field come back in markdown rendered to html rather than markdown?

**Comment by Thatkookooguy** [comment]
right now, everything you type in the bio is plain text. So if you type:
```
this is my **bio**!
```

it will show the `**` as text, and won't render it bold.

I think @megaxlr want the bio to support markdown so people can write a richer bio on their profile

**Comment by megaxlr** [comment]
That was indeed the point

**Comment by almeidamarcell** [comment]
I would like a markdown support for milestones :(

**Comment by skrollme** [comment]
+1

**Comment by pgreze** [comment]
+1

**Comment by sadam0930** [comment]
+1

**Comment by PAX523** [comment]
+1

**Comment by jacksao** [comment]
#505

**Comment by AnixPasBesoin** [comment]
Is this in github's roadmap?

**Comment by megaxlr** [comment]
@AnixPasBesoin Unlikely since this still marked as <needs clarification> even though there is a very clear definition from Thatkookooguy

**Comment by AnixPasBesoin** [comment]
@megaxlr that's a bummer!  Thanx for answering ^^

**Comment by filiptdz** [comment]
+1

**Comment by RobSchrage** [comment]
+1

**Comment by thomasfdm** [comment]
+1

**Comment by butterfly-pn** [comment]
+1

**Comment by mgomersbach** [comment]
+1

**Comment by stmoreau** [comment]
+1

**Comment by zerothi** [comment]
Bump issue, it has been clarified what was the intent

**Comment by megaxlr** [comment]
I'm rather thinking of closing it entirely since it seems like they dont care about this.

**Comment by mgomersbach** [comment]
Please don't. Closing it will only make it more unlikely.

**Comment by megaxlr** [comment]
But it will stop the chain of "+1" emails I have been getting. Its two years since we clarified the issue. The developers so clearly don't care about this issue there is no reason to keep it open. A label "Won't fix" is more likely than a fix.

**Comment by zerothi** [comment]
@megaxlr if you don't want mails, you can simply mute the thread :)
I.e. in the mail you receive for this correspondence there is a "mute thread" in the bottom. Then you can _forget about it_ :)

**Comment by stmoreau** [comment]
Maybe we are lucky and the new CEO really likes that feature and will push for it :joy: :joy: :joy: :joy:

**Comment by stmoreau** [comment]
I opened https://github.com/github-tools/github/issues/525 to have this issue open somewhere.

**Comment by aasmpro** [comment]
need Markdown every where :|

**Comment by thomasokken** [comment]
Lifting the 160-character limit would be nice as well. Whose bio fits in a tweet?!?
I just resorted to putting a link in there, but even that is a poor solution, because it is not clickable.

**Comment by j-rewerts** [comment]
It's worth noting here that I believe this was a misunderstanding. This project isn't responsible for GitHub.com. It's just a Javascript client library with an extremely unfortunate name. 

But agreed, GitHub should let us put more in our bio.

**Comment by sindelio** [comment]
The bio doesn't support markdown, such a simple feature to add :/

**Comment by DanielRuf** [comment]
This repository is not directly affiliated with github.com or its platform. This project is an API wrapper for JavaScript.
