### ISSUE TITLE
add a column with number of lines for source files in Code tab

### ISSUE THREAD

**Issue by awakenting** [github-tools/github#407]
Hey,

so first: is this the right place to make suggestions to improve the web interface of github ? If not, I guess you can point me to the right place ?

I realized recently that it often happens, that I want to look at the core functionality of a repository I am not familiar with and one useful heuristic for me is the number of lines in the source file. So I often end up clicking through many files with names that indicate core functionality but only have a few lines and I continue until I found one that has a lot of code which most often coincides with that it actually implements stuff.

Now I was wondering if this is an inconvenience for many other people and thought that it would be nice to have a column next to the file names that tells you the number of lines in that file. With that you could more easily scan the repository for the important source files. Alternatively, do you maybe know another way to do this with already existing functionality ? I already checked if you can sort search results by their size/number of lines, that would be another way to implement it.

I'm looking forward to hearing your thoughts on this :)

**Comment by clayreimann** [comment]
@awakenting Unfortunately, this is not how to get in touch with github. You could try [contacting them directly](https://github.com/contact)

**Comment by awakenting** [comment]
Oh, sorry then and thanks for the reply.

**Comment by awakenting** [comment]
fyi: I contacted them and the suggestion is in the right hands now so you can close this issue if you want
