### ISSUE TITLE
Release Version 3.1.0 is Not Available Via NPM

### ISSUE THREAD

**Issue by compumike08** [github-tools/github#436]
The latest release of this library in GitHub is version [`3.1.0`](https://github.com/github-tools/github/releases/tag/v3.1.0), however the latest version that can actually be [downloaded from NPM](https://www.npmjs.com/package/github-api) is `3.0.0`. When will version `3.1.0` be published to NPM?

@clayreimann 
@mtscout6 
@AurelioDeRosa 
@alexcanessa

**Comment by rudzon** [comment]
Any chances? Is this package abandoned?

**Comment by j-rewerts** [comment]
For those following this issue, 3.2 has been published.

**Comment by j-rewerts** [comment]
Check it out [here](https://github.com/github-tools/github/releases/tag/3.2.0).
