### ISSUE TITLE
Modified image file is not being updated.

### ISSUE THREAD

**Issue by rahuldeo2047** [github-tools/github#488]
Hi all,
I am looking for **the github** repo where I can submit an issue related to a file update failure/delay. Please guide me through.

## Issue: 
I think images with very small differences are not being reflected on github.

## What happens:
Please check the image file (image with a spelling mistake) ![image with spelling mistake](https://raw.githubusercontent.com/ROS-BLOCKS/design-ROS-Blocks/master/drawio/odometryW-design-ROS-Blocks.png) 
Another (corrected image file with same name, to show it in different name) ![image file](https://raw.githubusercontent.com/ROS-BLOCKS/design-ROS-Blocks/master/drawio/odometry2-design-ROS-Blocks.png) even if corrected/deleted and uploaded. The image file always remains as wrong one.

In order to show the error when I uploaded the file 2, the above file autocorrected. As shown it is no more in state of error. It has corrected itself.

FileName: odometry-design-ROS-Blocks.png
FileName showing wrong spell as a reference: odometryW-design-ROS-Blocks.png
FileName showing correct spell as a reference: odometry2-design-ROS-Blocks.png

## Possible ways of recreation:
0. Image name should be same "odometry-design-ROS-Blocks.png"
1. commit and push a png file with text in it as image. ![wrong image example](https://raw.githubusercontent.com/ROS-BLOCKS/design-ROS-Blocks/master/drawio/odometryW-design-ROS-Blocks.png) 
2. make a character change in the text, save as same image name, commit and push ![correct image](https://raw.githubusercontent.com/ROS-BLOCKS/design-ROS-Blocks/master/drawio/odometry2-design-ROS-Blocks.png)
3. Changes don't reflect on github repository web page or get delayed even after refresh.

I will be back with recreation.

**Comment by clayreimann** [comment]
I believe you're looking for the `Contact GitHub` link at the bottom of every page. We're not associated with github, we only make a JS api to talk to GitHub.

**Comment by rahuldeo2047** [comment]
OK Thank you.
Closing it here as the issue at a wrong repo.
