### ISSUE TITLE
Wrong API base

### ISSUE THREAD

**Issue by vivaxy** [github-tools/github#521]
https://github.com/github-tools/github/blob/master/lib/Requestable.js#L76

If path is '/repo//', should still add api base to the path.

**Comment by CodyGramlich** [comment]
I don't think there would be a situation where there would be double slashes in the URL. For repository names, if `/` is in the name, it gets replaced with `-`.

**Comment by vivaxy** [comment]
I thought it could be nicer if the method could tolerant some mistakes. The double slash mistake could be corrected when users passing params anyway. Thanks f
or your reply.
