### ISSUE TITLE
Please upgrade NPM to latest version

### ISSUE THREAD

**Issue by wuyxp** [github-tools/github#524]
In version 3.0.0
` ` `
const searchData = await this.github.search().forRepositories
` ` `
There are still some mistakes
There will be a constant entry to next that cannot be stopped.
I see the fix in version 3.1.0 of the current project, but it has not been released to NPMJS

**Comment by j-rewerts** [comment]
@clayreimann I second this. It'd be nice to push out a new release one of these days. I'd also be interested in learning what our release process looks like.

**Comment by clayreimann** [comment]
@wuyxp Sorry for the long delay, `v3.2.0` is now live on npm.

@j-rewerts the library is deployed to npm automatically when a tag is pushed. It looks like I never generated a new deploy token after that npm token leak debacle. I think I've got it sorted out now though.

**Comment by j-rewerts** [comment]
@clayreimann Thanks!
