### ISSUE TITLE
Bio doesn't support markdown

### ISSUE THREAD

**Issue by stmoreau** [github-tools/github#525]
The Bio text area on https://github.com/settings/profile doesn't support markdown as it used to.

[This issue](https://github.com/github-tools/github/issues/344) was heavily supported by the community. It was open since 2016, was labeled as "needs clarification" and got closed due to inactivity just today.

**Comment by j-rewerts** [comment]
@stmoreau Hi Stephane. I'm new to the project so bear with me.

It seems to me from the thread you referenced that people are under the impression that GitHub's bio doesn't support markdown (it doesn't as far as I can tell). If I have that right, it's probably worth mentioning that this repo doesn't have anything to do with GitHub proper and is just a JavaScript client library that makes using GitHub's API easier. Maybe I'm missing something? 😕

**Comment by alimcmaster1** [comment]
@j-rewerts - thanks for the response! Could you suggest the correct repo to raise this issue in?

**Comment by j-rewerts** [comment]
Tbh, I'm not too sure. Maybe it could help if people contact GitHub support?
