### ISSUE TITLE
Allow commit message author and committer on delete file action

### ISSUE THREAD

**Issue by ekeren** [github-tools/github#526]
The commit message for file deletion is hardcoded, we would like to allow the same api as `writeFile`

The new signature should be:
`function deleteFile(branch, path, message, options, cb)`
instead of existing one:
`function deleteFile(branch, path, cb)`

message, option - should be optional

We already have the code that fixes this issue in our code base, if this request is approved we can open a pull request. 

Thanks in advanced

**Comment by j-rewerts** [comment]
Please submit this as a PR.
