### ISSUE TITLE
Searching content within <details> in issues.

### ISSUE THREAD

**Issue by Malvoz** [github-tools/github#528]
It is not possible to search for text-content that resides within `<details>` elements inside GitHub issues.

Try [searching this repo for the alphabet](https://github.com/github-tools/github/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+abcdefghijklmnopqrstuvwxyz) that is written inside this element:

<details><summary><b>The alphabet</b></summary>
abcdefghijklmnopqrstuvwxyz
</details>

**Comment by j-rewerts** [comment]
This seems like a GitHub issue. This repo is just for the `github-api` package.

**Comment by j-rewerts** [comment]
Try sending an email to support@github.com. I think they'd be interested in this!

**Comment by j-rewerts** [comment]
@clayreimann Feel free to close this.

**Comment by Malvoz** [comment]
@j-rewerts 

> Try sending an email to support@github.com

Thanks, will do!
