### ISSUE TITLE
 module "tty" is not defined 

### ISSUE THREAD

**Issue by huangjianke** [github-tools/github#537]
![image](https://user-images.githubusercontent.com/8692455/51071185-cef3f000-1687-11e9-8a90-b52b972031cd.png)
Used in wechat miniprogram

**Comment by j-rewerts** [comment]
@huangjianke Could you post some code for us to see? We might be able to help sort out why this is happening.

**Comment by huangjianke** [comment]
@j-rewerts Thanks, The problem has been solved
