### ISSUE TITLE
Current project status - Maintainers wanted

### ISSUE THREAD

**Issue by DanielRuf** [github-tools/github#539]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by clayreimann** [comment]
@DanielRuf Not by me. Can't speak to @aendrew, @AurelioDeRosa, or some of the other usual suspects from when I worked on the project. But given that we're going on 18 months w/o a commit I think we could use some new blood

**Comment by AurelioDeRosa** [comment]
Things have definitely changed for me since I contributed to this project. So, new contributors are very welcome.

**Comment by clayreimann** [comment]
@AurelioDeRosa it looks like you and Ændrew are the only to admins in `github-tools` so you guys are the only ones who will be able to onboard new contributors. I've updated the readme with a link to this issue so if you see notifications in the near future it would be great if volunteers were addressed quickly.

**Comment by j-rewerts** [comment]
How would I go about becoming more actively involved?

**Comment by j-rewerts** [comment]
It looks like it has the odd PR to review. 😄 

I have contributions I'd like to make as well, though they may have been made in one of the PRs.

**Comment by clayreimann** [comment]
@j-rewerts if you wanted to start reviewing PRs I can merge PRs that you think look good. 

Unfortunately I can’t give you write access myself

**Comment by j-rewerts** [comment]
No worries! I'll familiarize myself with the project and make a couple changes. Then I'll start looking through the list. Would you or some of the other current maintainers be willing to work with me in the transition period?

**Comment by AurelioDeRosa** [comment]
@clayreimann I just made you an owner of this repo. I hope this unlock the situation.

**Comment by CodyGramlich** [comment]
I'm interested in contributing to this project too

**Comment by clayreimann** [comment]
@codygramlich that’s good to hear. Feel free to start reviewing open PRs. If you tag me in a comment saying that a PR is good, a duplicate, or can be closed I’ll get on it

**Comment by kylejeske** [comment]
> Things have definitely changed for me since I contributed to this project. So, new contributors are very welcome.

I'd be interested in contributing. Let me know how I can be of some use.

**Comment by clayreimann** [comment]
@kylejeske I would echo the same advice I gave to @j-rewerts and `DanielRuf`
> Feel free to start reviewing open PRs. If you tag me in a comment saying that a PR is good, a duplicate, or can be closed I’ll get on it
Though now you'll be able to tag @j-rewerts, as I've just given him write access as well.

**Comment by WJXHenry** [comment]
Hi! I'd like to contribute to this repo as well.

**Comment by tamer1an** [comment]
Hi I also have some parts done on my side for branch protection

**Comment by CCAtAlvis** [comment]
Count me in!! This project seems really good!

**Comment by DanielRuf** [comment]
@CCAtAlvis this is a NodeJS project. Not sure if this is ok for you regarding your GitHub bio / profile description.

**Comment by CCAtAlvis** [comment]
@DanielRuf ohh ya 😆😆 My bio is more of a memeish thing. I have been working with node for quite sometime now (although much of that work remains in private repos)

**Comment by aendrew** [comment]
Hi all, apologies for not jumping into this issue sooner.

I'm absolutely happy to hand over privileges to anyone who seems able to manage the project properly; my own OSS contributions have declined pretty dramatically and I really don't have time to maintain this anymore. 

Because it has a rather-large user base, I'd prefer someone with past experience contributing to open source projects — I'd really like to avoid an [event-stream](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)-like thing happening.

**Comment by DanielRuf** [comment]
> Because it has a rather-large user base, I'd prefer someone with past experience contributing to open source projects — I'd really like to avoid an [event-stream](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)-like thing happening.

I would be happy to maintain it and apply my strict security rules to it and collaborate with Liran Tal from Snyk as we did already for Verdaccio and so on =)

**Comment by ramigs** [comment]
I'd also like to contribute to this project.

**Comment by FreakinKat** [comment]
I usually Do not contribute, off this accout, but I can lend some of my time to see if anything needs a tweak or 2, or just over all Keep close eye out for anyone trying to turn it into an "event-stream- like thing" may not be much but integrity means alot to me and the author wants that so I guess i can be the buzz killer for those who try?

**Comment by aendrew** [comment]
@DanielRuf It'd be _amazing_ if you want to maintain it, have looked through your commit history and you seem above board 😄

Will pass privs to you and leave it up to you how you want to manage additional contributors. 👍

**Comment by DanielRuf** [comment]
@aendrew thank you, I have accepted the invitation and I'll create a more detailed plan in the next days and go through open issues and PRs.

**Comment by mattaharish** [comment]
Hey, this project seems interesting, i would like to start contributing.

**Comment by Vishesh30** [comment]
Hey this is exactly what i was looking for . I would also like to contribute maybe to astart by adding support for github enterprise as i work with that ..! :)

**Comment by nasirhjafri** [comment]
Hi, looks like interesting project. I would like to be maintainer.

**Comment by sustained** [comment]
I'll look into the code and see if I understand it enough, if I do maybe I could help at least somewhat.

I have a lot of experience, it's just that I never wrote an API wrapper before.

**Comment by AlQaholic007** [comment]
Hi @aendrew I would love to maintain and contribute to the project if possible. I've been using it for quite some time now and have looked at and understood the code base as well

**Comment by maneeshms** [comment]
Hi @aendrew , I am also interested to contribute to the project.

**Comment by Borumer** [comment]
Hello, I would like to contribute to this open source!

**Comment by JakeKo** [comment]
I would also like to contribute to this project.

**Comment by 9trocode** [comment]
I would love to contribute to this project

**Comment by kaus2595** [comment]
Hi @aendrew I would like to contribute in the project

**Comment by garimasingh128** [comment]
I would also like to contribute to this project.

**Comment by CoffeeGuyIRL** [comment]
Hi, i would love to maintain this project, and have also maintained other previous projects 😁

**Comment by j-rewerts** [comment]
Hi @garimasingh128 and @FrostyTheDumDum! Apologies for not responding sooner. The last time I worked on this project, the decision had been made to deprecate this library (#564). That being said, if we had a few people that could maintain the library, maybe that would change. Either way, it would be work, as deprecating this library in favour of OctoKit would require some work probably.

If you'd like to contribute, please get your environment set up. I'm going to update the getting started guide so it doesn't depend on my test user. Feel free to email me at jaredrewerts@gmail.com for assistance. Once you've got a few PRs in, I'll start working on getting you ownership over build/release if you're interested.

**Comment by FrostyTheDumDum** [comment]
Hi @j-rewerts thanks for replying, I'll start working on some PRs as soon as possible :)

**Comment by rilysh** [comment]
Hi there. It's been more than one year last commit was done. From there GitHub have a lot more updates recently, and I'd like to maintain GitHub.js. Can anyone kindly add me here via a GitHub organizational invite? Or should I fork it instead? What do you prefer folks?

**Comment by the-watchmaker** [comment]
Hi, I would like to maintain. I just started building an app around it. Would love to contribute.

**Comment by DanielRuf** [comment]
@the-watchmaker feel free to provide PRs and provide solutions to open issues.
