### ISSUE TITLE
Cannot enter text when creating a gist

### ISSUE THREAD

**Issue by normoes** [github-tools/github#555]
I use `Mozilla Firefox 66.0.2` with the following plugins installed:
* Decentraleyes
* Privacy Badger
* AdBlocker Ultimate
* Ghostery

Now, when I try to create a new gist, I cannot  edit the main text field - It's just disabled.
I can edit the description field and the file name field though.

On Chrome it is working perfeclty.

**Comment by kthy** [comment]
I'm seeing the same today with Firefox 69.0.1, uBlock Origin and the DuckDuckGo Privacy Essentials add-on.

**Comment by j-rewerts** [comment]
Sorry @normoes and @kthy, this isn't actually a repo for GitHub proper. This is actually just a JavaScript client library.

**Comment by kthy** [comment]
Fair enough 😁 I just ended up here through Google and didn't think to check where I was posting. Sorry for the noise!
