### ISSUE TITLE
Update Axios version from "^0.15.2" to "^0.19.0"

### ISSUE THREAD

**Issue by boiarqin** [github-tools/github#565]
There was a high-severity security vulnerability found in axios (see https://github.com/axios/axios/issues/2183). Axios released a new version 0.19.0 today to address the issue.

Thank you!

**Comment by j-rewerts** [comment]
I'll take a look at this soon.

**Comment by j-rewerts** [comment]
[For more information](https://github.com/axios/axios/issues/2183).

**Comment by j-rewerts** [comment]
My new test account was suspended 😢 I'm just waiting on GitHub support to reopen the account, then I can get the tests to pass and cut a new release in NPM.

**Comment by boiarqin** [comment]
Thank you--we really appreciate the status update!

**Comment by j-rewerts** [comment]
Closed with #567. v3.2.2 has been released.

**Comment by j-rewerts** [comment]
Let me know if you run into any more problems!

**Comment by kb0rg** [comment]
Thanks so much!

**Comment by boiarqin** [comment]
Thank you! 🙇‍♀
