### ISSUE TITLE
Incomplete Create Commit API 

### ISSUE THREAD

**Issue by rahulpsd18** [github-tools/github#576]
I think this API call is incomplete in the current version: https://developer.github.com/v3/git/commits/#create-a-commit

According to the documentation [here](https://github-tools.github.io/github/docs/3.1.0/Repository.html#commit), the implemented wrapper method expects `parent`, `tree` and `message` only (also callback) but the actual API supports `parents`, `tree`, `message`, `author`, `committer` and `signature`.

#413 will also get resolved once this is fixed.

**Comment by j-rewerts** [comment]
This was actually added recently, I just haven't updated the site yet. See the method signature [here](https://github.com/github-tools/github/blob/master/lib/Repository.js#L334).

Try it out and let me know if you run into problems!
