### ISSUE TITLE
bio field too short, doesn't support markup

### ISSUE THREAD

**Issue by thomasokken** [github-tools/github#584]
160 characters is very short for a bio (the text box under Edit Profile), and since you can't use any kind of mark-up in that box, even a clickable link to a proper bio is not possible. Could one or both of these restrictions be lifted?

**Comment by j-rewerts** [comment]
I think you may be mistaking this repo as being for GitHub proper. We're actually a community-run GitHub Javascript client library and have no relationship with GitHub.

**Comment by thomasokken** [comment]
Oops, you're right, I'm in the wrong place. Apologies, my bad!

**Comment by j-rewerts** [comment]
Not a problem! 😄
