### ISSUE TITLE
isStarred() example, callback errors

### ISSUE THREAD

**Issue by rontrek** [github-tools/github#585]
I am trying to do a `isStarred()` but getting error on callback if true or false, not sure if I am doing the right thing.

```
var gh = new GitHub({
   token: 'xxxxxxxx'
});

let repo = gh.getRepo({
	user: 'rontrek',
	repo: 'simple'
});

repo.isStarred(function(error, result, request) {
    console.log(request);
    if (error) {
        console.error(error);
        return;
    }
});
```
Console errors:
```
GET https://api.github.com/user/starred/[object%20Object] 404 (Not Found)
Error: 404 error making request get https://api.github.com/user/starred/[object Object]: "Not Found"(…)
```

**Comment by rontrek** [comment]
It's the unpkg dist (2.5.1?)

https://unpkg.com/github-api/dist/GitHub.bundle.min.js

**Comment by j-rewerts** [comment]
That's a super old release. Could I talk you into migrating to a newer version?

**Comment by rontrek** [comment]
Yes thanks, I will try it. btw, I assumed it was the latest because it is suggested in the project front page and readme.md

> ```
> 
> <script src="https://unpkg.com/github-api/dist/GitHub.min.js"></script>
> 
> 
> <script src="https://unpkg.com/github-api/dist/GitHub.bundle.min.js"></script>
> ```

Maybe update the cdn as well to the latest to avoid confusion.

**Comment by j-rewerts** [comment]
Oh nice catch!

**Comment by j-rewerts** [comment]
Closing. Let us know if you run into this issue in newer releases!
