### ISSUE TITLE
No topics are available when using getDetails.

### ISSUE THREAD

**Issue by sustained** [github-tools/github#590]
As you can see [here](https://developer.github.com/v3/repos/#get) the Github API provides a list of tags/topics however this library does not provide those to us when using `getDetails`.

**Comment by ramigs** [comment]
I've tried `GET` `repos/:owner/:repo` (as `getDetails` does) from curl, and didn't get the list of topics as well.

Seems to be related to the API itself (inconsistent docs??).

**Comment by sustained** [comment]
Could be.

I wonder how one reports an issue relating to the Github API...

**Comment by sustained** [comment]
I sent them an email.

**Comment by j-rewerts** [comment]
Let us know how it goes. I'll close this, but let me know if anyone wants it reopened.

**Comment by sustained** [comment]
> Note: The topics property for repositories on GitHub is currently available for developers to preview. To view the topics property in calls that return repository results, you must provide a custom media type in the `Accept` header: `application/vnd.github.mercy-preview+json`.
