### ISSUE TITLE
Repository tests must be run synchronously

### ISSUE THREAD

**Issue by j-rewerts** [github-tools/github#594]
Our Repository `creating/modifiying` tests seem to rely on a test repo being created prior to them being run. This makes it challenging to debug individual tests, and it also prohibits running multiple tests simultaneously. 

We can solve this 1 of 2 ways:
1. Every test initialises it's own test repositories. 
This seems like it'd be slow, but it may be worth it. Basically all of our tests are integration tests, so if we're determined to run our tests in parallel, we should do this way. If we can get GitHub to raise our test user accounts quota, this would let us run our test suite much more quickly.
2. Use the `before` function.
This would be extremely easy, but probably wouldn't allow us to run our tests in parallel with any consistency.

**Comment by DanielRuf** [comment]
Or we could run the tests in sequence which should be supported by most testrunners.

**Comment by j-rewerts** [comment]
Yeah after looking into Travis' documentation on parallel runners, it looks like it probably isn't worth the effort. We can reopen if our tests start to grow.
