### ISSUE TITLE
list commits on a pull request seems to be missing

### ISSUE THREAD

**Issue by otaviocx** [github-tools/github#598]
Hi, devs. There is an end-point in GitHub API that is for listing the commits inside a pull request: https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request. It seems that there is no function to map that end-point in Github.js. Could you please confirm if it is missing and if not, could you please say how can I do a request to this end-point? Thanks in advance!

**Comment by j-rewerts** [comment]
PR #599
