### ISSUE TITLE
GitHub Login page Freeze

### ISSUE THREAD

**Issue by Kamoba** [github-tools/github#601]
Hi,
I don't know if I'm on the right page to submit a bug on GitHub itself but, Houston i have a problem.

Every time I try to connect to GitHub from https://github.com/login and from my PC with Firefox or Brave browser the page takes about 4 minutes to fully load, before I can fill in my login information.
But no problem on Chrome and Edge.
Whether I disable the extensions or restart Firefox with the modules disabled it's always the same problem.

**Comment by j-rewerts** [comment]
Hey @Kamoba. This is actually a repo for a GitHub Javascript client library. We aren't directly associated with GitHub. I'd recommend contacting their [support](https://support.github.com/contact).
