### ISSUE TITLE
GitHub Gist: resize; preview

### ISSUE THREAD

**Issue by fabswt** [github-tools/github#608]
Hi there,

Any chance to offer Markdown preview and a resize button in the GitHub Gist editor?

While writing Markdown in a GitHub issue or comment is a delight, doing so in the GitHub Gist editor is a pain.

Thanks for reading!

**Comment by DanielRuf** [comment]
This repository is not directly affiliated with github.com or its platform. This project is an API wrapper for JavaScript.
