### ISSUE TITLE
Please add a Turkey country code support (+90) for SMS verification.

### ISSUE THREAD

**Issue by Animelici804** [github-tools/github#609]
I would like to have a second verification support, but due to the country codes not including Turkey, I can't add an SMS verification. If you would add the Turkey country code support, which is "+90", I would highly appreciate it.

Thanks for reading.
- Animelici804

**Comment by DanielRuf** [comment]
Hi @Animelici804,

this repository is not directly affiliated with GitHub the platform, it is `a minimal higher-level wrapper around Github's API.`.

Please contat the GitHub support at https://github.com/contact

**Comment by burakvnc** [comment]
i just changed input value to +90 and it worked

**Comment by ilhan-athn7** [comment]
> i just changed input value to +90 and it worked

Thanks for the idea 🫡
Edit: It it not worked for me.
