### ISSUE TITLE
Code review contributions in Github

### ISSUE THREAD

**Issue by Gahamelas** [github-tools/github#611]
This is a basic question, but... what counts as "code review" in the contribution graph in Github? Is it making comments on code or committing to code? I don't really understand the concept.

**Comment by DanielRuf** [comment]
Hi @Gahamelas,

It seems you confuse this repo (GitHub API client written in JavaScript) with the GitHub support but I try to answer your question.

Code review is when you go to a PR (pull request), go to the "Files changed" tab of it and provide feedback (approve, comment, request changes).

<img width="811" alt="Bildschirmfoto 2020-06-06 um 12 17 27" src="https://user-images.githubusercontent.com/827205/83941959-c0aff200-a7ef-11ea-890c-95242e51f1be.png">


As this has nothing to do with this client library I'm closing this issue.

**Comment by Gahamelas** [comment]
Thanks so much. At the cost of abusing your help...  Even if you don't comment, just approve a PR, will that be counting as code review?

**Comment by DanielRuf** [comment]
Yes, approving a PR counts as code review.

![IMG_20200607_175608](https://user-images.githubusercontent.com/827205/83973650-38614800-a8e8-11ea-80b2-2d2ccf748759.jpg)

**Comment by Gahamelas** [comment]
Thank you!
