### ISSUE TITLE
Misspelled Update

### ISSUE THREAD

**Issue by shivangdubey** [github-tools/github#613]
There is a minor spelling mistake in "Update" which appears while collaborating with other contributors. 
![issue](https://user-images.githubusercontent.com/55050487/83962681-0981ac80-a8bd-11ea-8d83-d67c41e6fcdc.jpg)

**Comment by DanielRuf** [comment]
Hi, this repository is about a JavaScript library for the GitHUb API and not affiliated with GitHub.

You may want to contact the GitHub support.

https://github.com/contact
