### ISSUE TITLE
Allow Collaborators to edit settings on a personal repository

### ISSUE THREAD

**Issue by Sanjay-B** [github-tools/github#615]
I don't think I can physically list out the number of times I've needed to go back and forth between a repo owner and myself over a settings dilemma (webhooks, secrets), etc. This poses a major development flow restriction since the repo owner and I are in different timezones. 

Github org would work in this case but, our workflow/development team isn't large enough to support an entire organization. It just makes zero sense to do so when a singular user account works perfectly fine. Eventually, there are plans to move it to an actual org but for now, we're both against it. 

Thanks.

**Comment by DanielRuf** [comment]
Hi @Sanjay-B,

This repository here is for a Nodejs / JS API module for GitHub and it is not affiliated with GitHub.

Please contact the GitHub support and check their community.

**Comment by DanielRuf** [comment]
> Github org would work in this case but, our workflow/development team isn't large enough to support an entire organization. It just makes zero sense to do so when a singular user account works perfectly fine

An org is a bit like a group and easy to setup. You can move the repo to it.
