### ISSUE TITLE
Open issue column on GitHub project

### ISSUE THREAD

**Issue by zzj0402** [github-tools/github#617]
Open issue column on GitHub project, like the GitLab:
![image](https://user-images.githubusercontent.com/15345547/87359211-7aeb0400-c5bb-11ea-8ac3-97201f52234b.png)

**Comment by DanielRuf** [comment]
Hi @zzj0402,

please check the repository description:

<img width="330" alt="Bildschirmfoto 2020-07-14 um 00 44 14" src="https://user-images.githubusercontent.com/827205/87360822-3172c880-c56b-11ea-934d-627f00c0a3ff.png">

This repository is not affiliated with GitHub Inc and this is not an official support channel for GitHub. Please use the options at https://github.com/contact
