### ISSUE TITLE
Hendra

### ISSUE THREAD

**Issue by suhendra775** [github-tools/github#622]
​<?​xml​ version​=​"​1.0​"​ encoding​=​"​UTF-8​"​?>
<!​DOCTYPE​ ​plist​ PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<​plist​ ​version​=​"​1.0​"​>
<​dict​>
  <​key​>Label</​key​>
  <​string​>com.<​username​>.grab_pkt</​string​>

  <​key​>ProgramArguments</​key​>
  <​array​>
    <​string​>/usr/local/bin/node</​string​>
    <​string​>/Users/<​username​>/development/misc/grab_packt/server.js</​string​>
  </​array​>

  <​key​>Nice</​key​>
  <​integer​>1</​integer​>

  <​key​>StartInterval</​key​>
  <​integer​>86400</​integer​>

  <​key​>RunAtLoad</​key​>
  <​true​/>

  <​key​>StandardErrorPath</​key​>
  <​string​>/tmp/GrabPkt.err</​string​>

  <​key​>StandardOutPath</​key​>
  <​string​>/tmp/GrabPkt.out</​string​>
</​dict​>
</​plist​>

**Comment by DanielRuf** [comment]
@suhendra775 please stop opening issues in this project.
