### ISSUE TITLE
Assigned task Feature

### ISSUE THREAD

**Issue by ritiksoni00** [github-tools/github#625]
If any contributor is working in a very waste area of opensource and let's assume that he get assigned for the 100+ issues. for keep eyes on the assigned issue, there should bee a feature like the "Assigned issues".

**Comment by DanielRuf** [comment]
Hi @ritiksoni00,

please check the repository description:

<img width="330" alt="Bildschirmfoto 2020-07-14 um 00 44 14" src="https://user-images.githubusercontent.com/827205/87360822-3172c880-c56b-11ea-934d-627f00c0a3ff.png">

This repository is not affiliated with GitHub Inc and this is not an official support channel for GitHub. Please use the options at https://github.com/contact

**Comment by ritiksoni00** [comment]
ohkayy!

**Comment by DanielRuf** [comment]
Regarding your question, see https://github.com/issues

**Comment by DanielRuf** [comment]
And there you can click on the "assigned" tab: https://github.com/issues/assigned

![IMG_20200820_095328](https://user-images.githubusercontent.com/827205/90732225-16fae000-e2cb-11ea-89af-6b3402ee5458.jpg)

**Comment by DanielRuf** [comment]
Same is also available on a per repository label afaik.

**Comment by DanielRuf** [comment]
The same is also available on a per repository level afaik.
