### ISSUE TITLE
README.md profile for organisations

### ISSUE THREAD

**Issue by darshan-jain** [github-tools/github#627]
How cool it would be if organisations could use the readme.md feature for describing more about their functioning.
This would not only help in the user understanding their repos, it will be easy for the contributors to know more about the firm at a glimpse

**Comment by DanielRuf** [comment]
Hi @zzj0402,

please check the repository description:

<img width="330" alt="Bildschirmfoto 2020-07-14 um 00 44 14" src="https://user-images.githubusercontent.com/827205/87360822-3172c880-c56b-11ea-934d-627f00c0a3ff.png">

This repository is not affiliated with GitHub Inc and this is not an official support channel for GitHub. Please use the options at https://github.com/contact

**Comment by zzj0402** [comment]
Why I am mentioned exactly?

**Comment by DanielRuf** [comment]
> Why I am mentioned exactly?

Sorry, my fault. I copied a response from another issue. You can ignore / unsubscribe from this issue here.

**Comment by darshan-jain** [comment]
Thank you @DanielRuf .  Hope you are keeping safe
