### ISSUE TITLE
update axios to v0.21+

### ISSUE THREAD

**Issue by ljharb** [github-tools/github#633]
There's a CVE for axios < v0.21: https://github.com/advisories/GHSA-4w2v-q235-vp99

similarly to #565, could a version be released that updates axios to latest?

**Comment by NetaNir** [comment]
Hi! 

The AWS CDK also requires this upgrade. If this can be done in a minor version release - happy to submit a pull request.

**Comment by j-rewerts** [comment]
This fix is in v3.4.0.

**Comment by ljharb** [comment]
Thank you!
